image:
  file: .gitpod.Dockerfile
ports:
  - port: 36541
    onOpen: open-preview
tasks:
  - init: pip install -r requirements.txt
    command: python server.py
vscode:
  extensions:
    - ms-python.python