include:
  - project: coscine/tools/gitlab-ci-templates
    file: 
      - /docker-runner.yml

stages:
  - build

.prepare:
  image: tobix/pywine
  before_script:
    - wine pip install --user --upgrade pip
    - wine pip install wheel
    - wine pip install -r requirements.txt
    - wine python -m nltk.downloader punkt

build-branch:
  extends: .prepare
  stage: build
  script:
    - wine pyinstaller server.py
  artifacts:
    paths:
      - dist
    expire_in: 1 yrs
