include:
  - project: coscine/tools/gitlab-ci-templates
    file: 
      - /docker-runner.yml

stages:
  - build

.prepare:
  image: python
  before_script:
    - pip install pyinstaller
    - pip install -r requirements.txt

build-branch:
  extends: .prepare
  stage: build
  script:
    - pyinstaller server.py
  artifacts:
    paths:
      - dist
    expire_in: 1 yrs
