include:
  - project: coscine/tools/gitlab-ci-templates
    file: 
      - /docker-runner.yml

stages:
  - build
  - container

.prepare:
  image: tobix/pywine
  before_script:
    - wine pip install --upgrade setuptools
    - wine pip install wheel
    - wine pip install gensim-4.1.2-py3-none-any.whl
    - wine pip install -r requirements.txt
    - wine python -m nltk.downloader punkt

build-branch:
  extends: .prepare
  stage: build
  script:
    - wine pyinstaller server.py
  artifacts:
    paths:
      - dist
    expire_in: 1 yrs
  rules:
    - when: manual

container:
  stage: container
  tags:
    - runner:docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    # variables can be overridden by extending the task
    # name of the container, uses project name (+path) by default
    CONTAINER_LABEL: latest
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_PROJECT_PATH:$CONTAINER_LABEL
  rules:
    - when: manual
