name: DevContainer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/BenediktHeinrichs/metadataextractor-devcontainer
          cacheFrom: ghcr.io/BenediktHeinrichs/metadataextractor-devcontainer
          push: always
          runCmd: sudo sh ./installDependencies.sh
