# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Test

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pip --upgrade
        chmod +x installDependencies.sh
        sudo ./installDependencies.sh
        pip install flake8
        # Deal with SSL errors: https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check
        pip install pyopenssl --upgrade
        # https://stackoverflow.com/questions/74982124/sam-build-from-github-actions-suddenly-failing-today-module-lib-has-no-attrib
        pip install --upgrade cryptography==38.0.4
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test by running the pipeline_runner
      run: |
        sudo java -jar ./tika-server.jar &
        sudo python pipeline_runner.py
